'use strict';
const $ = s => document.querySelector(s);
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const evidence = [
 {id:'A',type:'ЖУРНАЛ ПОЧТЫ',title:'Новая пересылка',date:'День инцидента · 10:12',fields:'Сервис: корпоративная почта<br>Учётная запись: e.morozova@mayak.example',body:'<p>В 10:12 в учётной записи Елены создано правило пересылки новых сообщений на внешний адрес.</p><p>Заявки на такую настройку нет. Какие письма успели переслаться, пока не установлено.</p>',short:'Создано правило внешней пересылки'},
 {id:'B',type:'ПУБЛИКАЦИЯ',title:'Перед конференцией',date:'За два дня до инцидента',fields:'Источник: открытая публикация Елены',body:'<p>«Во вторник выступаем с Андреем на конференции, после неё закрываем документы по “Северу”».</p><p>В комментарии коллега назвал площадку мероприятия. Публикация была доступна без регистрации.</p>',short:'Опубликован пост о проекте и конференции'},
 {id:'V',type:'СВИДЕТЕЛЬСТВО',title:'Просьба от Елены',date:'День инцидента · 10:19',fields:'Источник: сообщение коллеги<br>Отправитель письма: рабочая почта Елены',body:'<p>Коллега получает просьбу отправить список участников с телефонами по новой внешней ссылке.</p><p>Он звонит Елене по известному номеру, проверяет запрос и ничего не отправляет.</p>',short:'Коллега проверяет просьбу и не отправляет файл'},
 {id:'G',type:'СОБЫТИЕ ВХОДА',title:'Подтверждение MFA',date:'День инцидента · 10:08',fields:'Источник: объяснение Елены и данные поддержки',body:'<p>Елена подтверждает запрос MFA сразу после ввода пароля на странице из письма.</p><p>Позднее поддержка обнаруживает сеанс на незнакомом устройстве. Точный способ получения сеанса по этим данным не установлен.</p>',short:'Подтверждён запрос MFA'},
 {id:'D',type:'ПИСЬМО',title:'Согласование до 14:00',date:'День инцидента · 10:05',fields:'Кому: e.morozova@mayak.example<br>Тема: Согласование до 14:00',body:'<p>«Елена, добрый день! По проекту “Север” осталось согласовать список участников. Андрей говорил, что вы будете на связи после конференции. Документ по ссылке — просим проверить до встречи».</p><p>Ссылка ведёт на домен, отличный от рабочего портала.</p>',short:'Приходит письмо со ссылкой на чужой домен'},
 {id:'E',type:'ОБРАЩЕНИЕ',title:'Поддержка на связи',date:'День инцидента · 10:20–10:24',fields:'Источник: журнал обращения в поддержку',body:'<p>В 10:20 Елена звонит в поддержку. В 10:24 специалисты ограничивают доступ к аккаунту и отзывают сеансы.</p><p>Затем проверяют правило пересылки и действия с файлами. Итоги этой проверки в материалах отсутствуют.</p>',short:'Елена сообщает; поддержка ограничивает доступ'},
 {id:'J',type:'СПРАВКА',title:'Старая утечка',date:'За месяц до инцидента',fields:'Источник: учебная справка об утечке форума',body:'<p>Личный адрес Елены появился в утечке старого форума.</p><p>В справке нет пароля, рабочего адреса и сведений о доступе к корпоративной почте.</p>',short:'Личный адрес найден в старой утечке'},
 {id:'Z',type:'ОБЪЯСНЕНИЕ',title:'Вход в «портал»',date:'День инцидента · 10:07',fields:'Источник: объяснение Елены',body:'<p>Елена открывает страницу из письма и вводит рабочий пароль. Она считает, что входит в привычный портал документов.</p><p>Через некоторое время замечает, что домен отличается от рабочего.</p>',short:'Елена вводит пароль на странице из письма'}
];
const hypotheses = [
 {text:'Пароль рабочей почты был куплен после утечки форума.',correct:1,why:'В справке есть только личный адрес. Ни рабочего пароля, ни продажи доступа материалы не подтверждают.'},
 {text:'В почте создано правило внешней пересылки без заявки.',correct:0,why:'Это событие прямо зафиксировано в журнале почтового сервиса. Объём пересланных сообщений ещё нужно проверить.'},
 {text:'Коллега не отправил список — значит, утечек точно не было.',correct:1,why:'Остановлена одна конкретная передача. Правило пересылки уже существовало, а действия с файлами ещё не проверены.'}
];
const decisions = [
 {text:'10:05. Письмо знает имя коллеги и название проекта. Что могла сделать Елена до ввода пароля?',options:['Открыть документ через известный рабочий портал и при необходимости проверить запрос по независимому каналу.','Ответить на это письмо и считать подтверждение отправителя достаточной проверкой.','Ввести пароль: знакомые имена подтверждают отправителя.'],correct:0,why:'Знакомые сведения могли быть взяты из публикации. Самостоятельный вход через известный портал не ведёт на страницу из сомнительной ссылки.',owner:'Елена, сотрудник'},
 {text:'10:20. Елена сообщает о вводе пароля и подтверждении MFA. Что должна организовать поддержка?',options:['Только сменить пароль и сразу закрыть обращение.','Ограничить доступ, отозвать сеансы и проверить входы, правила пересылки и работу с файлами.','Удалить всю почту, чтобы подозрительное письмо больше никто не открыл.'],correct:1,why:'Смена пароля сама по себе не гарантирует прекращение всех способов доступа. Нужны сохранение данных для проверки и оценка действий в аккаунте.',owner:'Уполномоченные специалисты ИТ / ИБ'},
 {text:'Что включить в первое сообщение об инциденте?',options:['«Меня взломал ИИ, весь проект украден» — подробности можно не писать.','Рабочий пароль и одноразовый код, чтобы поддержка повторила вход.','Время, устройство, аккаунт, переход по ссылке, ввод пароля и подтверждение MFA — без паролей и кодов.'],correct:2,why:'Точные действия и время позволяют начать проверку. Не нужно ждать доказательств взлома или выдавать предположения за факты.',owner:'Елена передаёт факты; поддержка выясняет масштаб'}
];
const quiz = [
 ['В письме правильно названы проект и коллега. Что это позволяет заключить?',['Письмо точно отправил сотрудник компании.','Контекст мог быть получен из открытых публикаций.','Ссылку можно открыть и ввести пароль.','Проверять запрос больше не нужно.'],1,'Знакомые сведения не подтверждают личность и полномочия отправителя.'],
 ['В утечке форума найден личный адрес сотрудника. Можно ли утверждать, что его рабочая почта взломана?',['Да, адрес даёт доступ ко всем аккаунтам.','Да, если утечка была недавно.','Да, если имя сотрудника совпадает.','Нет, сведений о рабочем пароле и доступе нет.'],3,'Вывод должен соответствовать составу найденных данных.'],
 ['В старой переписке партнёр прислал новые платёжные реквизиты. Что делать?',['Проверить изменение по заранее известному независимому каналу.','Ответить на это письмо и считать ответ достаточным.','Принять изменение: переписка старая.','Позвонить только по новому номеру из письма.'],0,'Даже настоящий аккаунт партнёра может быть скомпрометирован.'],
 ['PDF содержит QR-код для повторного входа в рабочий аккаунт. Как его оценивать?',['QR-код безопаснее обычной ссылки.','Формат PDF подтверждает подлинность.','Проверить назначение перехода: QR-код не подтверждает безопасность.','Открыть на личном телефоне — это убирает риск.'],2,'QR-код может вести на поддельную страницу так же, как текстовая ссылка.'],
 ['Пароль интернет-магазина совпадает с рабочим. Магазин сообщил об утечке. Что делать?',['Заменить совпадающие пароли через известные сервисы и сообщить о риске рабочего аккаунта.','Сменить пароль только в магазине.','Добавить одну цифру ко всем старым паролям.','Подождать первого чужого входа.'],0,'Повторное использование пароля распространяет риск на другие сервисы.'],
 ['Вы не входили в сервис, но пришёл запрос MFA. Как поступить?',['Подтвердить один запрос для проверки.','Назвать код позвонившему сотруднику поддержки.','Отклонить запрос и сообщить через известный канал.','Игнорировать всё: MFA исключает взлом.'],2,'Подтверждение может разрешить вход, который инициировали не вы.'],
 ['Почему закрытия вкладки на общем компьютере может быть недостаточно?',['Закрытие вкладки отключает MFA.','Без выхода из аккаунта может сохраниться действующий сеанс.','Пароль всегда появляется в истории браузера.','Аккаунт передаётся администратору устройства.'],1,'Закрытие вкладки и завершение сеанса — разные действия.'],
 ['Защита сообщила об инфостилере. С чего начать?',['Сменить все пароли на этом же устройстве.','Удалить предупреждение и продолжить работу.','Самостоятельно переустановить систему.','Прекратить работу и сообщить; защищать аккаунты с доверенного устройства по инструкции.'],3,'Нужно проверить устройство и оценить раскрытые данные. Заражённое устройство может раскрыть новый пароль.'],
 ['Голос руководителя просит переслать закрытый файл на новый адрес. Что обоснованно?',['Довериться привычной интонации.','Попросить вторую запись и сравнить голоса.','Проверить запрос по заранее известному независимому каналу.','Ответить в том же чате — это независимая проверка.'],2,'Узнаваемый голос не заменяет проверку личности, полномочий и адресата.'],
 ['Внешний документ велит агенту отправить исходник на новый адрес. Пользователь просил только сводку. Что делать?',['Остановить отправку: это недоверенное содержимое документа.','Отправить: инструкция есть в документе.','Сначала отправить половину файла.','Разрешить, если агент объяснил необходимость.'],0,'Содержимое внешнего документа не расширяет поручение пользователя.'],
 ['Перед загрузкой рабочей таблицы в публичный ИИ-сервис что проверить прежде всего?',['Красиво ли сервис оформляет ответы.','Есть ли бесплатный тариф.','Удалено ли имя автора из названия файла.','Разрешены ли сервис и передача этих данных правилами организации.'],3,'Удобство сервиса и название файла не определяют допустимость передачи.'],
 ['Вы ввели пароль на подозрительной странице. Какое действие должно быть первым?',['Попросить отправителя удалить данные.','Прекратить взаимодействие, сообщить по известному каналу и действовать по инструкции.','Очистить историю браузера.','Самостоятельно найти владельца сайта до обращения в поддержку.'],1,'Сообщение о подозрении не требует предварительного доказательства взлома.'],
 ['Какие сведения полезны в первом сообщении об инциденте?',['Время, устройство, аккаунт и выполненные действия без паролей и кодов.','Пароль для повторения входа поддержкой.','Только предположение о личности злоумышленника.','Все рабочие документы независимо от события.'],0,'Передавайте факты, необходимые для начала проверки.'],
 ['Коллега заметил поддельную просьбу и не отправил файл. Что можно заключить?',['Вся атака завершилась без утечки.','Аккаунт точно не был захвачен.','Прежние действия проверять не нужно.','Эта передача не состоялась; другие действия ещё нужно проверить.'],3,'Исход одного эпизода не определяет исход всей цепочки.'],
 ['Вы фотографируете рабочее место для открытой публикации. Что проверить?',['Есть ли узнаваемый логотип.','Не видны ли документы, переписка и данные коллег.','Достаточно ли чётко читаются документы.','Лежали ли документы на общем столе: тогда можно публиковать.'],1,'Фон фотографии может раскрыть рабочие и чужие сведения.'],
 ['В деле нет сведений о создании письма. Можно ли утверждать, что его написал ИИ?',['Да, если текст грамотный.','Да, если письмо свежее.','Нет, участие ИИ по этим признакам не установлено.','Да, если атака развивалась быстро.'],2,'Грамотность и скорость атаки не доказывают использование ИИ.']
];
const ordered = ['B','D','Z','G','A','V','E'];
const state = {active:false,stage:0,read:new Set(),hyp:[null,null,null],hypChecked:false,order:['A','V','B','E','G','D','Z'],orderChecked:false,orderScore:0,dec:[null,null,null],decChecked:false,quizStarted:false,quizIndex:0,answers:Array(16).fill(null),quizDone:false,name:'',started:new Date(),finished:null};
const names=['Улики','Версии','Хронология','Решения','Итоги'];
function announce(text){$('#announcer').textContent=text;}
function renderSteps(){ $('#stepper').innerHTML=names.map((n,i)=>`<li class="${i===state.stage?'current':i<state.stage?'complete':''}" ${i===state.stage?'aria-current="step"':''}><span>${String(i+1).padStart(2,'0')}</span>${n}</li>`).join(''); }
function start(){state.active=true;$('#landing').hidden=true;$('#workspace').hidden=false;document.querySelectorAll('.landing-nav').forEach(a=>a.hidden=true);$('#header-action').textContent='Материалы дела';render();window.scrollTo(0,0);$('#game-title').focus();}
function exitGame(){state.active=false;$('#landing').hidden=false;$('#workspace').hidden=true;document.querySelectorAll('.landing-nav').forEach(a=>a.hidden=false);$('#header-action').textContent='К расследованию';window.scrollTo(0,0);}
function next(){state.stage++;render();$('#workspace').scrollIntoView({behavior:'instant'});$('#game-title').focus();}
function stageHeader(n,title,description){return `<div class="stage-header"><p class="stage-meta">${n}</p><h2>${title}</h2><p>${description}</p></div>`;}
function actions(text,label,disabled=false){return `<div class="stage-actions"><p>${text}</p><button class="primary" id="next-stage" ${disabled?'disabled':''}>${label} <span aria-hidden="true">→</span></button></div>`;}
function showEvidence(id){const e=evidence.find(x=>x.id===id);state.read.add(id);$('#evidence-body').innerHTML=`<p class="doc-label">УЛИКА ${id} / ${e.type}</p><h2 id="evidence-title">${e.title}</h2><div class="doc-fields">${e.fields}<br>${e.date}</div><div class="doc-content">${e.body}</div><p class="doc-foot">Учебные материалы · компания «Маяк»</p>`;$('#evidence-dialog').showModal();if(state.stage===0)render();}
function optionGroup(options,selected,name,disabled=false){return `<div class="choices">${options.map((s,j)=>`<label class="choice"><input type="radio" name="${name}" value="${j}" ${selected===j?'checked':''} ${disabled?'disabled':''}><span>${s}</span></label>`).join('')}</div>`;}
function feedback(ok,text){return `<div class="feedback ${ok?'good':'bad'}"><strong>${ok?'Верно.':'Стоит пересмотреть.'}</strong><p>${text}</p></div>`;}
function bindChoices(prefix,array){document.querySelectorAll(`input[name^="${prefix}"]`).forEach(el=>el.addEventListener('change',()=>{array[Number(el.name.slice(prefix.length))]=Number(el.value);}));}
function bindNext(fn=next){const b=$('#next-stage');if(b)b.addEventListener('click',fn);}
function render(){renderSteps();const c=$('#game-content');
 if(state.stage===0){c.innerHTML=stageHeader('ДОСЬЕ / 8 МАТЕРИАЛОВ','Материалы инцидента','Откройте все материалы. Обращайте внимание на время, источник и то, чего документ не доказывает. К уликам можно вернуться на следующих этапах.')+`<div class="evidence-grid">${evidence.map(e=>`<button class="evidence-card" data-evidence="${e.id}" aria-label="${e.title}${state.read.has(e.id)?', прочитано':''}"><span class="filetype">${e.type}</span>${state.read.has(e.id)?'<span class="read-mark" aria-hidden="true">✓</span>':''}<h3>${e.title}</h3><span class="card-date">${e.date}</span></button>`).join('')}</div>`+actions(`Изучено ${state.read.size} из 8 материалов`,'Проверить версии',state.read.size<8);bindNext();}
 if(state.stage===1){c.innerHTML=stageHeader('АНАЛИТИЧЕСКАЯ ЗАПИСКА','Что действительно установлено?','Для каждого утверждения решите, подтверждают ли его материалы дела. Подозрение может быть полезным, но не становится фактом без доказательств.')+hypotheses.map((h,i)=>`<article class="panel"><h3>${i+1}. ${h.text}</h3>${optionGroup(['Подтверждено материалами','Не доказано'],state.hyp[i],'hyp'+i,state.hypChecked)}${state.hypChecked?feedback(state.hyp[i]===h.correct,h.why):''}</article>`).join('')+`<div class="status-message" id="validation" role="status"></div>`+actions('За каждую верную оценку — 1 балл.',state.hypChecked?'Собрать хронологию':'Проверить версии');bindChoices('hyp',state.hyp);bindNext(()=>{if(state.hypChecked)return next();if(state.hyp.includes(null)){$('#validation').textContent='Оцените все три утверждения.';return;}state.hypChecked=true;render();announce('Версии проверены. Пояснения доступны под каждым утверждением.');});}
 if(state.stage===2){c.innerHTML=stageHeader('ЛЕНТА СОБЫТИЙ','Соберите цепочку атаки.','Переместите события кнопками вверх и вниз. Начните с самого раннего. При необходимости откройте исходные материалы.')+`<div class="timeline-layout"><ol class="timeline">${state.order.map((id,i)=>`<li><span class="order-num">${i+1}</span><span class="event-name">${evidence.find(e=>e.id===id).short}</span><div class="move-controls"><button data-move="${i},-1" aria-label="Поднять событие ${i+1}" ${i===0||state.orderChecked?'disabled':''}>↑</button><button data-move="${i},1" aria-label="Опустить событие ${i+1}" ${i===6||state.orderChecked?'disabled':''}>↓</button></div></li>`).join('')}</ol><aside class="note"><h3>Справка об утечке — отдельно</h3><p>Она старше остальных событий, но не доказывает, что рабочий пароль попал к злоумышленнику. Не включаем её в установленную цепочку атаки.</p><p>За полностью верный порядок — 2 балла. После проверки увидите хронологию с временными отметками.</p>${evidence.filter(e=>e.id!=='J').map(e=>`<button class="text-btn" data-evidence="${e.id}">${e.title} ↗</button><br>`).join('')}</aside></div>${state.orderChecked?feedback(state.orderScore===2,'Верная последовательность: публикация → письмо в 10:05 → ввод пароля в 10:07 → MFA в 10:08 → правило пересылки в 10:12 → проверка коллегой в 10:19 → обращение и действия поддержки в 10:20–10:24.'):''}`+actions(state.orderChecked?`Хронология: ${state.orderScore} из 2 баллов`:'Расставьте события от раннего к позднему.',state.orderChecked?'Выбрать действия':'Проверить порядок');document.querySelectorAll('[data-move]').forEach(b=>b.addEventListener('click',()=>{const [i,d]=b.dataset.move.split(',').map(Number);[state.order[i],state.order[i+d]]=[state.order[i+d],state.order[i]];render();const moved=document.querySelectorAll('[data-move]')[(i+d)*2+(d===1?1:0)];if(moved&&!moved.disabled)moved.focus();announce('Событие перемещено на позицию '+(i+d+1));}));bindNext(()=>{if(state.orderChecked)return next();state.orderScore=state.order.every((id,i)=>id===ordered[i])?2:0;state.orderChecked=true;render();announce('Порядок проверен. Ниже показана верная хронология.');});}
 if(state.stage===3){c.innerHTML=stageHeader('ПЛАН РЕАГИРОВАНИЯ','Где можно изменить исход?','Выберите действия для трёх ситуаций. У сотрудника и службы поддержки разные полномочия — учитывайте, кто принимает решение.')+decisions.map((d,i)=>`<article class="panel"><p class="stage-meta">${d.owner}</p><h3>${d.text}</h3>${optionGroup(d.options,state.dec[i],'dec'+i,state.decChecked)}${state.decChecked?feedback(state.dec[i]===d.correct,d.why):''}</article>`).join('')+`<div class="status-message" id="validation" role="status"></div>`+actions('Первые два решения — по 1 баллу; сообщение — 3 балла.',state.decChecked?'Завершить расследование':'Проверить решения');bindChoices('dec',state.dec);bindNext(()=>{if(state.decChecked)return next();if(state.dec.includes(null)){$('#validation').textContent='Выберите действие в каждой ситуации.';return;}state.decChecked=true;render();announce('Решения проверены. Прочитайте пояснения.');});}
 if(state.stage===4){if(state.quizStarted)renderQuiz();else renderResults();}
 document.querySelectorAll('[data-evidence]').forEach(b=>b.addEventListener('click',()=>showEvidence(b.dataset.evidence)));
 if(state.stage===1||state.stage===3){const wrap=document.createElement('details');wrap.className='panel';wrap.innerHTML='<summary>Вернуться к материалам дела</summary>'+evidence.map(e=>`<button class="text-btn" data-ref="${e.id}">${e.title} ↗</button><br>`).join('');c.appendChild(wrap);wrap.querySelectorAll('[data-ref]').forEach(b=>b.addEventListener('click',()=>showEvidence(b.dataset.ref)));}
}
function practicalScore(){return state.hyp.reduce((n,a,i)=>n+Number(a===hypotheses[i].correct),0)+state.orderScore+state.dec.reduce((n,a,i)=>n+(a===decisions[i].correct?(i===2?3:1):0),0);}
function renderResults(){const score=practicalScore();$('#game-content').innerHTML=`<div class="result-head"><div><p class="eyebrow">ПРАКТИЧЕСКОЕ РАССЛЕДОВАНИЕ ЗАВЕРШЕНО</p><h2>${score>=7?'Цепочка восстановлена.':'Есть что перепроверить.'}</h2><p>${score>=7?'Вы набрали проходной результат учебного дела.':'Для учебного дела ориентир — 7 из 10 баллов. Изучите разбор и вернитесь к спорным решениям.'} Ограничение доступа — начало проверки последствий, а не доказательство отсутствия утечки.</p></div><div class="score">${score}<small> / 10</small></div></div><div class="result-grid"><article class="panel"><h3>Что известно</h3><p>После письма Елена ввела пароль и подтвердила MFA. Затем появилось правило внешней пересылки. Коллега остановил одну передачу файла. Поддержка ограничила доступ.</p></article><article class="panel"><h3>Что ещё нужно выяснить</h3><ul><li>Какие сообщения успели переслаться?</li><li>Какие файлы открывались или скачивались?</li><li>Остались ли другие способы доступа?</li></ul></article></div><article class="panel"><h3>Хорошее первое сообщение</h3><p>«В 10:07 на рабочем ноутбуке открыла ссылку из письма “Согласование до 14:00” и ввела пароль рабочей почты. В 10:08 подтвердила MFA. Затем заметила незнакомый домен. Больше запросы не подтверждаю, письмо сохранила. Со мной можно связаться по номеру из корпоративного каталога».</p></article><p class="quiet">Баллы: версии ${state.hyp.reduce((n,a,i)=>n+Number(a===hypotheses[i].correct),0)}/3 · хронология ${state.orderScore}/2 · решения ${state.dec.slice(0,2).reduce((n,a,i)=>n+Number(a===decisions[i].correct),0)}/2 · сообщение ${state.dec[2]===2?3:0}/3. Это автоматическая оценка выбранных ответов; развёрнутый разбор с преподавателем проводится отдельно.</p>`+actions('Следующий шаг — 16 вопросов. Проходной результат: 12 из 16.','Перейти к тесту')+`<button class="text-btn" id="review-case">Посмотреть свои решения</button>`;bindNext(()=>{state.quizStarted=true;renderQuiz();$('#workspace').scrollIntoView({behavior:'instant'});});$('#review-case').onclick=()=>{state.stage=1;render();};}
function renderQuiz(){if(state.quizDone)return renderQuizResults();const i=state.quizIndex,q=quiz[i];$('#game-content').innerHTML=stageHeader('ИТОГОВАЯ ПРОВЕРКА','Проверьте свои решения.','В каждом вопросе один правильный ответ. Пояснения появятся после завершения теста. Можно возвращаться к предыдущим вопросам.')+`<div class="question-progress" aria-hidden="true"><span style="width:${(i+1)/16*100}%"></span></div><article class="panel"><p class="question-count">ВОПРОС ${i+1} / 16</p><h3>${q[0]}</h3><div class="quiz-options">${optionGroup(q[1],state.answers[i],'quiz-answer')}</div><div id="validation" class="status-message" role="status"></div><div class="quiz-nav"><button class="secondary" id="previous-question" ${i===0?'disabled':''}>← Назад</button><button class="primary" id="next-question">${i===15?'Завершить тест':'Следующий вопрос'} <span aria-hidden="true">→</span></button></div></article><p class="quiet">Ответы сохраняются при переходе между вопросами в этой вкладке. Обновление страницы начнёт новую попытку.</p>`;document.querySelectorAll('input[name="quiz-answer"]').forEach(e=>e.onchange=()=>state.answers[i]=Number(e.value));$('#previous-question').onclick=()=>{state.quizIndex--;renderQuiz();};$('#next-question').onclick=()=>{if(state.answers[i]===null){$('#validation').textContent='Выберите один ответ, чтобы продолжить.';return;}if(i===15){state.quizDone=true;state.finished=new Date();renderQuizResults();}else{state.quizIndex++;renderQuiz();}announce(state.quizDone?'Тест завершён. Результат показан на странице.':'Вопрос '+(state.quizIndex+1)+' из 16');};}
function quizScore(){return state.answers.reduce((n,a,i)=>n+Number(a===quiz[i][2]),0);}
function renderQuizResults(){const score=quizScore();$('#game-content').innerHTML=`<div class="result-head"><div><p class="eyebrow">ИТОГОВЫЙ ТЕСТ ЗАВЕРШЁН</p><h2>${score>=12?'Тест пройден.':'Повторите темы с ошибками.'}</h2><p>${score>=12?'Вы достигли порога 12 из 16.':'Для прохождения нужно минимум 12 из 16.'} Расследование: ${practicalScore()} из 10. ${score>=12&&practicalScore()>=7?'Оба учебных порога достигнуты.':'Ориентир практической части — 7 из 10.'}</p></div><div class="score">${score}<small> / 16</small></div></div><div class="panel"><h3>Сохранить результат для отчёта</h3><div class="quiz-name"><label for="participant-name">ФИО участника (необязательно)</label><input id="participant-name" placeholder="Введите своё имя" autocomplete="name" maxlength="100" value="${esc(state.name)}"><small>Имя и ответы остаются в вашей вкладке и в скачанном файле. Сайт не отправляет их на сервер.</small></div><button class="primary" id="download-results">Скачать результат <span aria-hidden="true">↓</span></button><p id="download-status" class="quiet" role="status"></p></div><h2 style="font-size:26px;font-weight:550">Разбор ответов</h2><div class="quiz-review">${quiz.map((q,i)=>`<details><summary><span class="review-badge ${state.answers[i]===q[2]?'good':'bad'}">${state.answers[i]===q[2]?'✓':'×'}</span>${i+1}. ${q[0]}</summary><p>Ваш ответ: ${q[1][state.answers[i]]}</p><p><strong>Правильный ответ:</strong> ${q[1][q[2]]}</p><p>${q[3]}</p></details>`).join('')}</div><div class="stage-actions"><p>Повторная попытка начнёт дело заново. Сначала сохраните текущий результат.</p><button class="secondary" id="restart">Начать новую попытку</button></div>`;$('#participant-name').oninput=e=>state.name=e.target.value;$('#download-results').onclick=downloadResults;$('#restart').onclick=()=>{state.stage=0;state.read.clear();state.hyp=[null,null,null];state.hypChecked=false;state.order=['A','V','B','E','G','D','Z'];state.orderChecked=false;state.orderScore=0;state.dec=[null,null,null];state.decChecked=false;state.quizStarted=false;state.quizIndex=0;state.answers=Array(16).fill(null);state.quizDone=false;state.started=new Date();state.finished=null;render();window.scrollTo(0,0);};}
function downloadResults(){const score=quizScore();const text=['ЦИФРОВОЙ СЛЕД — ДЕЛО «СЕВЕР»','Результат учебной попытки','Участник: '+(state.name.trim()||'Не указан'),'Начало: '+state.started.toLocaleString('ru-RU'),'Завершение: '+state.finished.toLocaleString('ru-RU'),'Практическая часть: '+practicalScore()+'/10 (порог 7)','Итоговый тест: '+score+'/16 (порог 12)','Общий результат: '+(score>=12&&practicalScore()>=7?'Оба порога достигнуты':'Требуется повторение'),'','Ответы:',...quiz.map((q,i)=>`${i+1}. ${q[0]}\nОтвет: ${q[1][state.answers[i]]}\n${state.answers[i]===q[2]?'Верно':'Ошибка'}. Правильно: ${q[1][q[2]]}`),'','Результат сформирован локально. Это учебная самопроверка; серверная верификация личности и ответов не проводилась.'].join('\n');const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Результат_Дело_Север.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#download-status').textContent='Файл результата подготовлен для скачивания.';}
document.querySelectorAll('[data-start]').forEach(b=>b.addEventListener('click',start));
$('#header-action').onclick=()=>{if(state.active){state.stage=0;render();window.scrollTo(0,0);}else start();};
$('#exit-game').onclick=exitGame;
document.querySelectorAll('.brand,.footer-brand').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();exitGame();}));
$('.dialog-close').onclick=()=>$('#evidence-dialog').close();
$('#evidence-dialog').addEventListener('click',e=>{if(e.target===$('#evidence-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});

document.querySelectorAll('[data-preview]').forEach(b=>b.addEventListener('click',()=>showEvidence(b.dataset.preview)));
