'use strict';

// This is a separate simulation. The original case keeps its fixed evidence.
const scene = {step:0,mail:'request',choices:[],details:false,link:false,portal:false,report:[],notes:'',active:false};
const storyRoot=document.querySelector('#story');
const safeText=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function storyOutcome(choices){
 const exposed=choices[0]==='enter', sent=choices[1]==='send', contained=exposed&&choices[2]==='contain';
 return {exposed,sent,contained,session:exposed&&!contained,
  title:exposed?(contained?'Доступ прекращён. Последствия ещё нужно проверить.':'Посторонний сеанс остался активным.'):(sent?'Пароль сохранён, но список участников отправлен.':'Пароль и список участников не переданы.'),
  records:[
   {id:'M1',time:'10:05',title:'Входящее письмо',text:'В письме упомянуты Андрей и проект «Север». Адрес отправителя: files@mayak-docs.example. Кнопка ведёт на portal-mayak.example. В рабочей переписке указан другой портал: portal.mayak.example.'},
   {id:'M2',time:'10:08',title:'Действия Елены',text:exposed?'Елена ввела рабочий пароль на странице из письма и подтвердила вход. В учебном сценарии посторонний получил активный сеанс почты.':'Елена открыла портал по адресу из прежней рабочей переписки. Документа там не было. Андрей по известному номеру подтвердил, что не отправлял просьбу. Елена не вводила пароль на странице из письма.'},
   ...(exposed?[{id:'M3',time:'10:12',title:'Журнал почты',text:'В учётной записи Елены появился сеанс на незнакомом устройстве и правило пересылки на внешний адрес. Какие сообщения были пересланы, пока неизвестно.'}]:[]),
   {id:'M4',time:'10:19',title:'Решение коллеги',text:sent?'Коллега загрузил список участников с номерами телефонов на внешний сайт. Елена позже сообщила, что не просила отправлять файл.':'Коллега позвонил Елене по номеру из корпоративного каталога. Она не подтвердила просьбу. Коллега не отправил список.'},
   {id:'M5',time:'10:24',title:'Действия поддержки',text:exposed?(contained?'Поддержка ограничила доступ, завершила активные сеансы, сменила пароль и отключила внешнюю пересылку. Журналы сохранены; проверка действий с письмами и файлами продолжается.':'Поддержка сменила пароль и закрыла обращение. В этой учебной системе смена пароля не завершает активные сеансы. Посторонний сеанс и правило пересылки остались.'):(choices[2]==='investigate'?'Поддержка сохранила письма и проверила входы. Неизвестных сеансов не обнаружено. '+(sent?'Передачу списка зарегистрировали как инцидент и начали выяснять получателей данных.':'Подозрительную ссылку заблокировали и предупредили получателей письма.'):'Поддержка закрыла обращение без проверки. '+(sent?'Передачу списка не зарегистрировали, получателей данных не установили.':'Не выяснено, кто ещё получил такое письмо.'))}
  ]};
}
function launchStory(){scene.active=true;document.querySelector('#landing').hidden=true;document.querySelector('#workspace').hidden=true;storyRoot.hidden=false;document.querySelectorAll('.landing-nav').forEach(a=>a.hidden=true);document.querySelector('#header-action').textContent='Обзор дела';paintStory();storyRoot.scrollIntoView({behavior:'instant'});}
function leaveStory(){scene.active=false;storyRoot.hidden=true;exitGame();}
function storyReset(){Object.assign(scene,{step:0,mail:'request',choices:[],details:false,link:false,portal:false,report:[],notes:'',active:true});paintStory();storyRoot.scrollIntoView({behavior:'instant'});}
function storyButton(label,value){return `<button class="story-choice" data-decision="${value}">${label}<span aria-hidden="true">→</span></button>`;}
function storyMail(){
 const earlier=scene.mail==='earlier';
 return `<div class="mail-shell"><nav class="mail-list" aria-label="Письма"><p>Входящие <span>2</span></p><button data-mail="request" aria-pressed="${!earlier}"><small>10:05 · Документы проекта</small><strong>Согласование до 14:00</strong><span>Елена, добрый день! По проекту…</span></button><button data-mail="earlier" aria-pressed="${earlier}"><small>Вчера · Андрей Волков</small><strong>Документы к встрече</strong><span>Работаем в обычном портале…</span></button></nav><article class="mail-reader"><p class="story-label">${earlier?'Вчера, 16:40':'Сегодня, 10:05'}</p><h3>${earlier?'Документы к встрече':'Согласование до 14:00'}</h3><p class="mail-sender">${earlier?'Андрей Волков':'Документы проекта Север'} <button class="text-btn" id="mail-details" aria-expanded="${scene.details}">Показать адреса</button></p>${scene.details?`<dl class="mail-address"><dt>От</dt><dd>${earlier?'a.volkov@mayak.example':'files@mayak-docs.example'}</dd><dt>Кому</dt><dd>e.morozova@mayak.example</dd></dl>`:''}<div class="mail-copy">${earlier?'<p>Елена, привет!</p><p>Документы к встрече складываем в рабочий портал <strong>portal.mayak.example</strong>, в папку «Север». Если появится новый файл на согласование, я позвоню.</p><p>Андрей</p>':`<p>Елена, добрый день!</p><p>По проекту «Север» осталось согласовать список участников. Андрей говорил, что вы будете на связи после конференции. Просим проверить документ до встречи.</p><button class="document-link" id="inspect-link" aria-expanded="${scene.link}">Открыть документ ↗</button>${scene.link?'<div class="link-preview"><p>Адрес страницы</p><code>https://portal-mayak.example/sign-in</code><p>Страница предлагает войти с рабочей учётной записью. Выберите дальнейшее действие ниже.</p></div>':''}<p>С уважением,<br>Отдел сопровождения проекта</p>`}</div></article></div>`;
}
function sceneBody(){
 const exposed=scene.choices[0]==='enter';
 if(scene.step===0)return `<p class="story-role">Вы действуете от имени Елены · 10:05</p><h2 tabindex="-1" id="scene-title">Пришло письмо по проекту «Север»</h2><p class="story-intro">До встречи осталось немного времени. Прочитайте новое письмо. Предыдущая переписка тоже доступна.</p>${storyMail()}<div class="story-decision"><h3>Как поступить с документом?</h3>${storyButton('Открыть рабочий портал из прежней переписки и уточнить просьбу у Андрея','verify')}${storyButton('Войти на странице из нового письма и подтвердить запрос на вход','enter')}<p class="quiet">Это имитация почты. Ссылки не открывают внешние сайты, вводить настоящие пароли не нужно.</p></div>`;
 if(scene.step===1)return `<p class="story-role">Теперь вы действуете от имени коллеги · 10:19</p><h2 tabindex="-1" id="scene-title">Просьба отправить список участников</h2><p class="story-intro">${exposed?'Коллеге пришло письмо с рабочей почты Елены.':'Елена проверила первое письмо. Позже её коллега получил новую просьбу с адреса, похожего на рабочий.'} Решите, как ответить.</p><article class="mail-reader standalone"><p class="story-label">Новое сообщение</p><h3>Список для организаторов</h3><p class="mail-sender">Елена Морозова</p><details class="message-address"><summary>Показать адрес отправителя</summary><code>${exposed?'e.morozova@mayak.example':'e.morozova@mayak-team.example'}</code></details><div class="mail-copy"><p>Привет! Пришли, пожалуйста, список участников с телефонами. Организаторы собирают всё в новой папке: <span class="fake-link">files-sever.example/upload</span>.</p><p>Я сейчас на встрече, говорить неудобно. Нужно до 11:00.</p></div></article><div class="story-decision"><h3>Что сделает коллега?</h3>${storyButton('Позвонить Елене по номеру из корпоративного каталога','call')}${storyButton('Загрузить список по ссылке из письма','send')}</div>`;
 if(scene.step===2)return `<p class="story-role">Теперь вы специалист поддержки · 10:20</p><h2 tabindex="-1" id="scene-title">Елена сообщила о подозрительных письмах</h2><div class="support-chat"><p class="chat-name">Елена</p><p>${exposed?'В 10:07 я ввела пароль на странице из письма, а потом подтвердила вход. Позже заметила, что адрес сайта отличается от рабочего.':'Я открыла наш портал и позвонила Андрею. Он не отправлял письмо. На странице из письма я пароль не вводила.'}</p><p>${scene.choices[1]==='send'?'Коллега уже загрузил список участников по ссылке. Я его об этом не просила.':'Коллега получил просьбу от моего имени, но позвонил мне и не стал отправлять список.'}</p></div><article class="support-log"><h3>Данные первичной проверки</h3><p>${exposed?'10:08 — вход с незнакомого устройства.<br>10:12 — создано правило пересылки на внешний адрес.':'В обращении есть два подозрительных письма. Историю входов специалисты пока не проверяли.'}</p></article><div class="story-decision"><h3>Какие действия вы выполните?</h3>${exposed?storyButton('Ограничить доступ, завершить сеансы, сменить пароль и отключить пересылку. Сохранить журналы и проверить последствия','contain')+storyButton('Сменить пароль и закрыть обращение','password'):storyButton('Сохранить письма, проверить входы и передачу файлов, предупредить получателей','investigate')+storyButton('Закрыть обращение: Елена не вводила пароль','close')}</div>`;
 return storyReport();
}
function decisionResponse(){
 const step=scene.step,v=scene.choices[step];
 if(step===0)return v==='verify'?['10:08 · Разговор с Андреем','«Я не отправлял это письмо. В портале нового документа нет. Спасибо, что позвонила». Елена сохранила письмо для поддержки. Пароль на посторонней странице она не вводила.']:['10:08–10:12 · Запись событий','В этом сценарии после ввода пароля и подтверждения входа посторонний получил сеанс рабочей почты. В 10:12 в учётной записи создано правило пересылки.'];
 if(step===1)return v==='call'?['10:19 · Ответ Елены','«Я не просила отправлять список. Ничего не загружай, я обращусь в поддержку». Коллега сохранил письмо и не передал файл.']:['10:19 · Файл передан','Список участников с номерами телефонов загружен на внешний сайт. Позже Елена сказала, что не просила отправлять его. Удаление письма не вернёт переданный файл.'];
 const o=storyOutcome(scene.choices);return ['10:24 · Результат действий',o.records.at(-1).text];
}
function reportClaims(o){return [
 {text:o.exposed?'Елена ввела пароль на странице из письма.':'Елена не вводила пароль на странице из письма.',proof:'M2'},
 {text:o.sent?'Коллега передал список участников посторонним.':'Коллега не отправил список участников.',proof:'M4'},
 {text:'Участие искусственного интеллекта в подготовке письма доказано.',proof:'unknown'}
];}
function storyReport(){
 const o=storyOutcome(scene.choices);
 return `<p class="story-role">Заключение координатора · После 10:24</p><h2 tabindex="-1" id="scene-title">${o.title}</h2><p class="story-intro">Сопоставьте выводы с записями в журнале. Отметьте, что удалось установить, а что осталось неизвестным.</p><div class="case-outcome"><p><strong>Рабочая почта:</strong> ${o.exposed?(o.contained?'активные сеансы завершены':'посторонний сеанс остаётся активным'):'ввод пароля на постороннем сайте предотвращён'}.</p><p><strong>Список участников:</strong> ${o.sent?'передан на внешний сайт':'коллега его не отправил'}.</p><p><strong>Что ещё выяснить:</strong> ${o.exposed?'какие письма были пересланы и какие файлы открывали.':o.sent?'кто получил список и можно ли ограничить дальнейшее распространение.':'кто ещё получил подозрительные письма и как ответил на них.'}</p></div><div class="report-layout"><div><h3>Подтвердите выводы</h3>${reportClaims(o).map((c,i)=>`<label class="claim-label" for="proof-${i}">${i+1}. ${c.text}</label><select id="proof-${i}" data-proof="${i}"><option value="">Выберите основание</option>${o.records.map(r=>`<option value="${r.id}" ${scene.report[i]===r.id?'selected':''}>${r.id} · ${r.title}</option>`).join('')}<option value="unknown" ${scene.report[i]==='unknown'?'selected':''}>В материалах нет подтверждения</option></select>`).join('')}<label class="claim-label" for="case-notes">Что вы поручите проверить дальше? <span class="quiet">Необязательно</span></label><textarea id="case-notes" rows="4" maxlength="2000" placeholder="Укажите действие и исполнителя">${safeText(scene.notes)}</textarea><button class="primary" id="check-conclusion">Проверить заключение</button><div id="conclusion-feedback" role="status"></div></div><aside class="story-records"><h3>Журнал вашего сценария</h3>${o.records.map(r=>`<details><summary>${r.id} · ${r.time} · ${r.title}</summary><p>${r.text}</p></details>`).join('')}</aside></div><div class="story-finish"><button class="secondary" id="download-story">Скачать ход расследования</button><button class="secondary" id="replay-story">Попробовать другие решения</button><button class="text-btn" id="fixed-case">Перейти к учебному делу и тесту →</button><p class="quiet">В сценарии нет оценки за выбор пути. Тест и оценка из 10 баллов доступны в учебном деле с фиксированными материалами.</p><p id="story-download-status" role="status"></p></div>`;
}
function paintStory(){
 const chosen=scene.choices[scene.step]!==undefined&&scene.step<3;
 const response=chosen?decisionResponse():null;
 storyRoot.innerHTML=`<div class="story-top"><div><p class="eyebrow">ЦИФРОВОЙ СЛЕД / ИНТЕРАКТИВНЫЙ СЦЕНАРИЙ</p><h1>Один рабочий день</h1></div><button class="secondary" id="leave-story">Обзор дела</button></div><ol class="story-steps" aria-label="Этапы сценария">${['Письмо','Просьба','Поддержка','Заключение'].map((s,i)=>`<li ${scene.step===i?'aria-current="step"':''}>${i+1}. ${s}</li>`).join('')}</ol>${chosen?`<div class="story-response"><p class="story-role">${response[0]}</p><h2 tabindex="-1" id="scene-title">Что произошло после вашего решения</h2><p>${response[1]}</p><button class="primary" id="story-next">${scene.step===2?'Составить заключение':'Продолжить'} →</button></div>`:sceneBody()}`;
 document.querySelector('#leave-story').onclick=leaveStory;
 storyRoot.querySelectorAll('[data-mail]').forEach(b=>b.onclick=()=>{scene.mail=b.dataset.mail;scene.details=false;paintStory();});
 const details=document.querySelector('#mail-details');if(details)details.onclick=()=>{scene.details=!scene.details;paintStory();document.querySelector('#mail-details').focus();};
 const link=document.querySelector('#inspect-link');if(link)link.onclick=()=>{scene.link=!scene.link;paintStory();document.querySelector('#inspect-link').focus();};
 storyRoot.querySelectorAll('[data-decision]').forEach(b=>b.onclick=()=>{scene.choices[scene.step]=b.dataset.decision;paintStory();focusScene();});
 const next=document.querySelector('#story-next');if(next)next.onclick=()=>{scene.step++;paintStory();focusScene();};
 storyRoot.querySelectorAll('[data-proof]').forEach(s=>s.onchange=()=>{scene.report[Number(s.dataset.proof)]=s.value;document.querySelector('#conclusion-feedback').textContent='';});
 const notes=document.querySelector('#case-notes');if(notes)notes.oninput=()=>scene.notes=notes.value;
 const check=document.querySelector('#check-conclusion');if(check)check.onclick=()=>{const claims=reportClaims(storyOutcome(scene.choices));document.querySelector('#conclusion-feedback').innerHTML=claims.map((c,i)=>`<p>${!scene.report[i]?`${i+1}. Выберите основание для вывода.`:scene.report[i]===c.proof?`${i+1}. Верно. ${c.proof==='unknown'?'По тексту письма нельзя установить участие ИИ.':'Этот вывод подтверждён записью '+c.proof+'.'}`:`${i+1}. Проверьте запись ${c.proof==='unknown'?'о создании письма: таких сведений в деле нет':c.proof+'. Выбранная запись не подтверждает этот вывод'}.`}</p>`).join('');};
 const download=document.querySelector('#download-story');if(download)download.onclick=downloadStory;
 const replay=document.querySelector('#replay-story');if(replay)replay.onclick=storyReset;
 const fixed=document.querySelector('#fixed-case');if(fixed)fixed.onclick=()=>{scene.active=false;storyRoot.hidden=true;start();};
}
function focusScene(){document.querySelector('#scene-title').focus();storyRoot.scrollIntoView({behavior:'instant'});}
function downloadStory(){
 const o=storyOutcome(scene.choices);const claims=reportClaims(o);
 const text=['ЦИФРОВОЙ СЛЕД — ОДИН РАБОЧИЙ ДЕНЬ','Учебный сценарий с развилками',o.title,'',...o.records.map(r=>`${r.id} · ${r.time} · ${r.title}\n${r.text}`),'','Заключение участника:',...claims.map((c,i)=>`${c.text}\nВыбрано: ${scene.report[i]||'Не указано'}. ${scene.report[i]?(scene.report[i]===c.proof?'Основание выбрано верно.':'Основание требует проверки.'):'Вывод не проверен.'}`),'','Дальнейшая проверка:',scene.notes||'Не указана','','События вымышлены. Результат составлен из выбранных действий; это не результат реального инцидента.'].join('\n');
 const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Цифровой_след_сценарий.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);document.querySelector('#story-download-status').textContent='Файл подготовлен для скачивания.';
}
document.querySelectorAll('[data-story]').forEach(b=>b.onclick=launchStory);
const previousHeaderAction=document.querySelector('#header-action').onclick;
document.querySelector('#header-action').onclick=()=>{if(scene.active)leaveStory();else previousHeaderAction();};
document.querySelectorAll('.brand,.footer-brand').forEach(a=>a.addEventListener('click',()=>{scene.active=false;storyRoot.hidden=true;}));
